//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoCar
    {
        public int id { get; set; }
        public string serNum { get; set; }
        public string numStrah { get; set; }
        public string color { get; set; }
        public string @class { get; set; }
        public string year { get; set; }
    }
}
