//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoVod
    {
        public int id { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public string otchestvo { get; set; }
        public string numberPhone { get; set; }
        public Nullable<System.DateTime> dateStartWork { get; set; }
        public Nullable<int> staj { get; set; }
        public Nullable<double> reyting { get; set; }
        public string markaCar { get; set; }
        public string modelCar { get; set; }
    }
}
