//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class taxiEntities : DbContext
    {
        public taxiEntities()
            : base("name=taxiEntities")
        {
        }
        private static taxiEntities _context;

        public static taxiEntities GetContext()
        {
            if (_context == null)
                _context = new taxiEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accountVod> accountVod { get; set; }
        public virtual DbSet<classCar> classCar { get; set; }
        public virtual DbSet<infoCar> infoCar { get; set; }
        public virtual DbSet<infoVod> infoVod { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
