//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public string otkuda { get; set; }
        public string kuda { get; set; }
        public Nullable<int> typeService { get; set; }
        public Nullable<int> typeClass { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual classCar classCar { get; set; }
        public virtual service service { get; set; }
    }
}
